/*
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.qase.client.v1.models;

import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TestCaseParams
 */
public class TestCaseParamsTest {
    private final TestCaseParams model = new TestCaseParams();

    /**
     * Model tests for TestCaseParams
     */
    @Test
    public void testTestCaseParams() {
        // TODO: test TestCaseParams
    }

}
