/*
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.qase.client.v1.api;

import io.qase.client.v1.ApiException;
import io.qase.client.v1.models.ConfigurationCreate;
import io.qase.client.v1.models.ConfigurationGroupCreate;
import io.qase.client.v1.models.ConfigurationListResponse;
import io.qase.client.v1.models.IdResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConfigurationsApi
 */
@Disabled
public class ConfigurationsApiTest {

    private final ConfigurationsApi api = new ConfigurationsApi();

    /**
     * Create a new configuration in a particular group.
     *
     * This method allows to create a configuration in selected project. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createConfigurationTest() throws ApiException {
        String code = null;
        ConfigurationCreate configurationCreate = null;
        IdResponse response = api.createConfiguration(code, configurationCreate);
        // TODO: test validations
    }

    /**
     * Create a new configuration group.
     *
     * This method allows to create a configuration group in selected project. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createConfigurationGroupTest() throws ApiException {
        String code = null;
        ConfigurationGroupCreate configurationGroupCreate = null;
        IdResponse response = api.createConfigurationGroup(code, configurationGroupCreate);
        // TODO: test validations
    }

    /**
     * Get all configuration groups with configurations.
     *
     * This method allows to retrieve all configurations groups with configurations 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getConfigurationsTest() throws ApiException {
        String code = null;
        ConfigurationListResponse response = api.getConfigurations(code);
        // TODO: test validations
    }

}
