/*
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.qase.client.v1.api;

import io.qase.client.v1.ApiException;
import io.qase.client.v1.models.UserListResponse;
import io.qase.client.v1.models.UserResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    /**
     * Get a specific user.
     *
     * This method allows to retrieve a specific user. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserTest() throws ApiException {
        Integer id = null;
        UserResponse response = api.getUser(id);
        // TODO: test validations
    }

    /**
     * Get all users.
     *
     * This method allows to retrieve all users. 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUsersTest() throws ApiException {
        Integer limit = null;
        Integer offset = null;
        UserListResponse response = api.getUsers(limit, offset);
        // TODO: test validations
    }

}
