load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "4.3"
RULES_JVM_EXTERNAL_SHA = "6274687f6fc5783b589f56a2f1ed60de3ce1f99bc4e8f9edef3de43bdf7c6e74"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "org.junit:junit-bom:5.11.2",
        "org.junit.jupiter:junit-jupiter-api:5.11.2",
        "org.junit.jupiter:junit-jupiter-params:5.11.2",
        "org.junit.jupiter:junit-jupiter-engine:5.11.2",
        "org.junit.platform:junit-platform-console-standalone:1.11.4",
        "io.qase:qase-junit5-reporter:4.1.25",
        "org.aspectj:aspectjweaver:1.9.22",
        "org.aspectj:aspectjrt:1.9.22",
        "org.slf4j:slf4j-api:1.7.32"
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)

